[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7c2ba2004a15b2a9bd9f068305918c8b964a4a2"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "53969609d437d3d29034195f7091d956b8ba524331c999298476e96f849c3af1"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfedc6e6eb0194729c900e5e9f56978ed90a724c"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "8127dfcf8425d1c7b860cfa8157fc231bea0df7ad62337b057c079645462b2ef"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5adc17b07b68335201356d9b8ae130512bb2b98b"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "af14b9afbce02254e405c7c364cb60eb2c74f39abe5ac40f83c9b350b2f6d8cd"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.aarch64-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e4caed5c597c4741d8eda5341dc02fa029e859d"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "80522794313e34f1e1bd46d2558540bc7c636517c23c35d0cea4ed03934eaf9a"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.aarch64-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be00ed8c42f4358d02f25fe934b4a721e6a33c92"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "61f5f959a44c9aded26aad9e0404300d8ce691df1b2456ce53f0211a8764c71f"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed1a8fb69dbb3b569c5a7938e3f620a9fd732607"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "104fc26912473518b42a7c7c04fe3e960588f97ab690ea6bf457991bcfe7c397"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e635290a9b664a86da225a876bc5f33d7a1532cd"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "863712359cbf570d9d7d35f1291b4624e79025a76f16b52beebbe341bd5f8a59"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00164a0f2ffb0e2e82e01bca6d12f3c4e1236284"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "363ec8ea146948ce2fc9d6b42a17b7c1846d44f1738b38bf3730d428018f4665"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "933a6fc17b12a98f8e17eee123f473dc91f5fef8"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "9cce2e630c8ea0889c5c55632aae0d855b17d78995cb8a8a3bcd9672437ad15d"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.i686-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54a24e2b5e48e1639964c9cdcacdc0181abf23a7"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "c99f4de42fb52f349abfb7407dca8a8388d660c6876b8fe0634dc18f25d511ac"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.i686-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39dae5b401701f9739af96e6cefbb7b716bc4a1a"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "7b6c89176cda42591b1f1c00129274cc0062b657247664bd7630c4f39420fed9"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.i686-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e839f3f53e2ccdf2e0bb793378f68fd5f955609a"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "299487819d55d67f64060feb3fdd0132fb23aa93d64dc745e3d2110d3565ad6c"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.i686-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e954d4eb72d3b30de60c76aa82c9409df36c7c5"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "3233617e7ab41830e7e4bfe6e9e1bf68e48138552e7cd17c5c60216add72d96f"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.i686-w64-mingw32-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11af04b3cdb0941749ada4d267e33493ec6e1275"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "af3a18d92d105fd5510dc71d7c06353e56c774eb19618c4b73ab245fc08d9c09"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.i686-w64-mingw32-cxx11.tar.gz"
[[Chemfiles]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33696b672f7bfee9bf7be4d03105112b1be01caf"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "6340226be08f781b165e97a142c13c6c143975157898e8ddc6fc4dc7c56dafc8"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4b0fcf29e113535eab396e0186cacd40c171de8"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "dac940726b1bc39100754017de16a90468b385c1a7aa4fd36881e60c8cb591ab"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
git-tree-sha1 = "9b5fc6697848a1e9dc5aaf0ed7e0bafdf05899db"
os = "macos"

    [[Chemfiles.download]]
    sha256 = "6616dbf030a48cef2b5c8d0a18809d071baae71ecc7529c5fc42552faf50b841"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.x86_64-apple-darwin.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bea9b509b92fd21a6c4e20d43e7b73608ade3040"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "0f10f9aea88240576894e6cf9258858208106da366ed2f4b3d54fdc3b9ac725d"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95de56b8cbc3f2275fafc906b355e1c07446cc22"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "ebf7168b3f5509e7c0b2867d082ee0567ef87d289c494f7fd9c7e57ae1102231"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7342ec1ae5ce123c0f428361b9d42d0d6ce8831"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "02015558e7364d8986482c2d10ca8549620d76ae87f6a7542cda7a44e02ba24b"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.x86_64-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c305dea4e95a10b4b1a04a8f4926b7225782fea2"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "b0daba32f3e14ff9698d2552259355d2b5c5b88c35ca784a29fe9f2c04d473d6"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.x86_64-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
git-tree-sha1 = "089b76bf69cfb743f6bd6b17cbe50395034f0ad4"
os = "freebsd"

    [[Chemfiles.download]]
    sha256 = "62104134b9fedffba9c4b6797db7b4de19fc985e8ca57d24503f1748ae8764a9"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.x86_64-unknown-freebsd.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9ffb08d5ff484293058f47e20b4caa215c21b7f"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "9d629bcf6ec959a97f59e829ab74c1a4fce8ec52ba2b1793aef7b98ab33f9520"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a63ebb0148ac24595f7eed534582fe286cc11b1a"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "6657e268b941bc572b6e71045b245a962c84fc7bd0d213dad60a8c5df8d5a88d"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.0+0/Chemfiles.v0.10.0.x86_64-w64-mingw32-cxx11.tar.gz"
