[[Chemfiles]]
arch = "aarch64"
git-tree-sha1 = "1fe4c26d1ca338844055da48b3a1a2bb34f39144"
os = "macos"

    [[Chemfiles.download]]
    sha256 = "7aa6cd20dbf237efd55c66912c786a429b793c07c9ad002892b0065e59ec8c98"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.aarch64-apple-darwin.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59eede1b966788a58cef808a5c0977341acc6367"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "8bc5211ca9d0a7d65a0324eb67cad8e954bb622fc5e4aa6306d99433c207854a"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.aarch64-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17c61c4b6b660c13b3c05d7a1529801863ae7b19"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "b8c129048184f036f6f82fd5a2ff076b1df92dbcd063b1af518c7faf477a7aa2"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.aarch64-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1025c67ac2bfc00a5f7ac8a6a93664d1654dfb71"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "cbe7657e474f63d558675c46dfab225d78aee46198a2e1b5a8d253efa9379b20"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.aarch64-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9af92e6ca4bc8c1f1a36f560c4abe49af0c147e8"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "b98b3b1cabad19509dd6e42d8d3ba36cbe0657127a1f2479db7800768007fcc4"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.aarch64-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad976bf0e8f15512b8086deaab3842b191057893"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "fbabecb28976bca9ad7ac8050df2b6ffc047d1ccdcb4f194a9204e71226e52ee"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "086432c52cb4a530408e8e23e2b62b320573a728"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "8227264f6c479431029f22025cb3c584af4ebdf80c38ba134905e8124377f3c8"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a28ca19042f48aa349b33f66b7cbbb0459aa36a5"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "9e658c9c918cd7a4b66d009f52b4d85a59ed7d282c9ca5063cd6947cfe16c7c9"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d3b2fb63c51af52f180ef0c1e8b916696780220"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "ce600e8a689c2c8e227bacd81211631f153e13f48c225209c99a17fd4e69a53d"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df34ca30a7a02fed4743f5e5338f47807fb10fc4"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "bcc71a44b0ff4e9b9ab0c0195e06d906575177f53f599dc35fa400da4dcfc8d5"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "267186da14a4f12bddcb1be72e2e681d479ea269"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "c89fbada3fda2997f4b8459f1c7af52f7c8ca0aaa15302a89e116ddd64ccdffd"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90e01b5b01130fe2a97d23eb3fdcddbdaa6f4757"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "570ce566a3561d952d11cabb301633a90e031a49460bf774ff57c0bab81c36e7"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56a8ee41ce5ba260d8d0667e7e41ee8e0df14ce5"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "dc831359c526fccf90dfc1b51df51057f4201ec40de8784a7fc327db339206c9"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e81b77fb39e74efa7609a45943d6849d551848a2"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "86d351426ac24b0b63ae3a169475270d8542f94aac29e835ff5ed432a032150e"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.i686-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4e4c121ecdcee3c3d95d5b7ee568d4296694eea"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "dd255cc9ce6b805358a7e54ac14fc29206492cec8ae35143b1c260dcb3a875a0"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.i686-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96482adac4dc05708d4f0854e41890163113e0f5"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "26290280c74b9dc86fd0e10ecd4122f226db2c1713c8ebebe2d3ef3c4d69e6e3"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.i686-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a859c3ecaf4b97ad37680a2d335023140124b0b4"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "30c6a3829ceef73841b188c832215486489ac3603d427957db3bebf1b3a0514f"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.i686-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61bb3ad25fe25a2c745355c45a6cda68acede40e"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "85a04aae6e1ee940d52b24ae750220a5f1b28ae563cbbbcabd10d1f2cfbf3ec2"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.i686-w64-mingw32-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83c031f40b97c26a3e4d87c218baf8025fd51899"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "1e12396ea4e66075d53b1bbfb20cb104894a1a604c1f4698a18034de0d367e9b"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.i686-w64-mingw32-cxx11.tar.gz"
[[Chemfiles]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6404431e71b46c9e4a7ba9626089c7d3e4ff7119"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "4fbe19eff83b83c3ce118e3246901719e2eacff09a9313fba2850e91e80c14ee"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c1f2eb5a65f3e29cd5b5b04b1d9dff4f7facb24"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "cf655cb72a0d7eee69c6543daff7d91f3386e12aa0c7899838ca427a5c02e9a3"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
git-tree-sha1 = "bd9c1ddaac9e646cb3e4d412f308e41442da21c7"
os = "macos"

    [[Chemfiles.download]]
    sha256 = "6437cb12ac0e988a47dcbe7012e281044d3ca88c56c6472381fcbc4509f0d08e"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.x86_64-apple-darwin.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ffdf49572f5d82a30cac93f782989986e2931f3"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "b399de8d99ce25464e5f4c29c4b5d61b48a5ff86ce404376ea27e052ef00c6ed"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.x86_64-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6398bc0dc00247d60980385e150f1aef965ce2f2"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "89f04b64333bb1a2db844127669519da9d645aaba5a2d91060007c7a9e7195ab"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.x86_64-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11c898d08215a5c7e03f0d55adc7598bc974ff8a"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "b6435a48e9cc48a62478facb4f0cc0410cc0a4b58ddf63df4b787c159753c37c"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.x86_64-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bedd5d5d3991950aaf66900960a39c31540f7e8b"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "d51a4ebc6414f0bcc34008a1e6b8a86852372565c532b047893c984e40313a48"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.x86_64-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
git-tree-sha1 = "3c853835fe523592143073f02199dc3d7e60ae69"
os = "freebsd"

    [[Chemfiles.download]]
    sha256 = "52021e08debb6f3fa8dbf5bc7e154ec219f6a2526165bc651e67302104001555"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.x86_64-unknown-freebsd.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82dacd9b43346146d4cc3ae1ecdaf1bf8ff0a5d1"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "51aede0b37c2bde02add0c11ea74c57635b59de4d459833cbadc92c59c55ab99"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1873d4bb611435a80164b3328df68da3745bdfdf"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "b11fe095fe14c8c64e4c5b653e89d7ac0bd407faf41f0fb635e74d09001992bb"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.4+0/Chemfiles.v0.10.4.x86_64-w64-mingw32-cxx11.tar.gz"
