[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ad4457087309e0875eb31cce253851a5c66afb1"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "8c3bf277846e8d2c6278388ea6ed754d0b3699669d4ed1ce267bed8d8f2ffc2e"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2adb09d1c2b5cd2cf08eaf56b973d856c0f148f"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "cda398a69e0b2f77126833dce519b61eec4c379a203801fcc06506b287372fab"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0113aa3f701f15c4c0351007281c6889518b7c15"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "b5daf195d1b17bcc47a961240af433c48e61288b1d708a6df3142187ae89a795"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.aarch64-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4eadd814046a72abe7ca0c8d5ec84ca0a1d3ab1"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "f0dfe558cc109c8c7df682630c46e72241c3369678a477722bf06ed064ddd4f3"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.aarch64-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f192098bc1615c859eaf572a8ac4c7628d3e2db"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "5b8e3246d0d90b7ee3fc3370ef3c10e448842955812f16a55ed798e16f497c24"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "266c61207a84792be00c505e029b97daa3dcc51c"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "59dc17ffd3f5bac1a7c719baab9db39949c5ced802ea646daa7679052a68d598"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71bda52a3f28156a72b8a8c17a13e09a76933d4d"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "cd601578fe322d7f1e073a7d5cf399ac9b738e188478e5d0962ccb541df535dd"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddbb2d90f5e951c97455ec30814c7ea24f715ad7"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "aa0346081873b1e51c605596c4bba415fe59324a87d9cd6f40de57768404e2e3"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60877cba34e7ad355ebe8bfefa521e666e434c60"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "e571164d9b9f29bd18d319ccdd30f52f9b82a913d6a4432d4bbd126e84da2f79"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.i686-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f78239169d76b8e5831ef118adee33dc1f7ec4d"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "cd276c499c83f73f396e49371974a9feb5681c8247bfa9b23f1bf4b3a0fde066"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.i686-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65be94fd14cdd956f44828e4dc8a536c6b2e0585"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "1adc817ab41f204d68f7366589d7c5b43943e47489a5c02d4339a95b9396da22"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.i686-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b141e7ee3ed979e3ffd5609dc52dec32ba84c02"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "5cf1609b12ed33d6aa440e3bec248214cc8d0e0fe73acf3e5572f8fb1fcc1382"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.i686-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5387603f1c5848ea5929ad153172e33092f2c1fc"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "c037b41ec4feb247c14aed582f58225dac7702419c6370777bb15d28ced99434"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.i686-w64-mingw32-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70ac53bf1b0f8c281a0c89bb420b3a535a7f0914"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "dddeffbed57bb14ff5ada1ce9d17dc2e3be1bc84aa9562e49bd2bbead7892e07"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.i686-w64-mingw32-cxx11.tar.gz"
[[Chemfiles]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b735611d3ed753dcfb33e7fc6170ee8d234929a2"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "9119d88ab98582949eda926c77ef52294a2066cd93b7b9407584c5ca6e2c46b7"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deeed42835690945c7f61851561eec39ee8d870d"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "a58fcfc747aa3ae56841283a385d619356aaa599ecaf71ce93aadb165e720d6c"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
git-tree-sha1 = "ee8b88219bf59d874d07223c7f68ee96028dd0b8"
os = "macos"

    [[Chemfiles.download]]
    sha256 = "5cfbcde3c3979f65333ad4c0b894fe9a3922e7aed13e8c10c2fafa3165dff7da"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.x86_64-apple-darwin.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32199a5cbee9d81e09c332b994d3aa3038043f59"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "449f6ea2e64e753faca57ef11b1b7a73af357a396eacf51072b36e7a1d8aebd3"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da37b7bf87f6c97b1718da90136eb2793a0914fa"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "cfa42814faad11e26b10c18bdc74f6538b03cfcab1b59188525fc57f013e2820"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62e4015aa376acf5b515e13ac35dd98346488e56"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "a9d33deea6a101bf39d1b63dccddeec7ccc062c0da6372946cb17f0a2fc2424f"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.x86_64-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cfda700c0729d88d355093777b52b28fe1852f9"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "77a333de0f4b2a230f1d9944be5c62069a9dc0657e46b2aad0b2e58fee7d72c2"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.x86_64-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
git-tree-sha1 = "46f72dd760edffdeda09c5cdf5bc625b7c34e68c"
os = "freebsd"

    [[Chemfiles.download]]
    sha256 = "7540ef7c208d2f883ef90fdcf3c69fc3854e2766cad162602594bb769c0aab9c"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.x86_64-unknown-freebsd.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3563181acab83e36901921f2fa611eb4997c3ddc"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "5dc4779eae1351552018cc38462d49e4bc85a8baf8bf1bd8eade6fdab72fb858"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b172da733a9ece880d5c2298dee106679d980a7d"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "5542b93bc22bac6f2fec222b7f926ce50d9bfe6eb3019903d335208b08fc56ca"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.2+0/Chemfiles.v0.10.2.x86_64-w64-mingw32-cxx11.tar.gz"
