[[Chemfiles]]
arch = "aarch64"
git-tree-sha1 = "c270d596cec613468c48d194c26d2cc3a7434965"
os = "macos"

    [[Chemfiles.download]]
    sha256 = "454e9b25ab050925963a40fc4b83af40caf72c06c675124f52f0e261a48af55b"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.aarch64-apple-darwin.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83a6688bc04cce635aed67c6611924e74b6b1f0c"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "3482960d7b9e8d2429b804de5ed3a6a6fdc29a9fac6943e907bb68a022aad11f"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14ee19c870b7c76581923a020e4426e8400d5841"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "b5975658ef4dd3dafb5d26543941600e51b6825f1eab0a89881e08fd4fe2b2ac"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "814262d623c24d83d9b4f988c78fc1e75e8175c3"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "77270d1b87d34a8bf04bbf1ba7780861afd5042a888d173072318de53d109f8c"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.aarch64-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "067c767533f4e73775cd486bbc6a0de5781aafdb"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "50ee123667901f09f71da742a40a56608b8280ea2bde739922439fbb24eb3dce"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.aarch64-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d46cea62b02ebf2220564449b77a19e17833282d"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "cbd0fbfa3e2fdccf62dcf36b1ea09eaa17b9350672df73500a3d880cb6ffd735"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f0964e72469621ddc3da02a5c346c6b0a33ca2b"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "ffc30de4018ea4ea9e67104e15f05a21a5606e7df8e83a9228b958ddf95e259b"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c91f6e5b193959e9653949fe2e0fc9fb4e4b36d8"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "64da3217efbd55175eecef646690b8c557ecf15365136cc1ba6049c4ed08be03"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "673b0bb6c5306d4fb7c7f3b512d5a7145cf90c24"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "013723545666ead876be91407acc1b386be4ccae1899c9a5e4728426d391caf9"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8b7d4a2d6a61e228f578524e7963cc31f064f87"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "9233bf5e592993c33bb12443e654b15074a3fcad429b5b5fc61a0ead224c4d31"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c762df37c5018121fdec62f9545d52f3147163d0"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "c39da8e4a98dd01ce4aa730a2e9e19a9e06b72b82b1ce3d2d428cbcec04d3b92"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "918507ba7c91b2dd44b5fe32685f35fd288d8630"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "00078dd2ce5f45ee05d9fe3df525ad800efd87f33712796620930ab1b6e39ae6"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Chemfiles]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c48d1b24276f354aeb9fe650d5d2da60803a3ab0"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "20e89d8fe55c73cf42886a7432d11f5d0daf5e82adf5699256c4246cd248157f"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9b2fadb4a36d25bd8dbca927a97ea3f4c7a320c"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "afe3d9fd2b8b092a0329170e2ebaf51c33f3c87b6eeff4c471314a49213e956d"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.i686-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc6ba16c34711b9e7c11d48cb1aa51062df0942b"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "fc43175927d318023b8df545c9d7b8e75d61193bce93d9d600f1a191e5ebadcf"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.i686-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea5df1627ae72feec261c01778915da024094e05"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "fafc90a875d14b835df41cc4ee509a650f7fb5fbacfb710b5233cae432c1cf09"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.i686-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6e4dede4b418049639b8193a546aff9a9392760"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "2bd0bdd6f26c7e7abc10b96b551b358b1b21086e893cffa344df0d791d9f6ebd"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.i686-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df290ddc7cde695c71ddf4f7a40215d0aefc1469"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "c4a406e636f00b740be8f74b9173ead9c163096dbd664ab37470d3b4e6da78e4"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.i686-w64-mingw32-cxx03.tar.gz"
[[Chemfiles]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab93969e4e5ae9398dd9b3cfc1d010839f7e8f2e"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "34a550f396c677b15141e07750c312fae3ebc9b505767b5d724a1f2bc93dd3d9"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.i686-w64-mingw32-cxx11.tar.gz"
[[Chemfiles]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cc6e9f38da5b874d612ee63de12e62e2b6f069a"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "1e3a0b381db660a33772c3a592a8392338563853cf01bdd67ab9598cff74f60a"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2228b2230eeca6fa371824f45c2112f54099ec4"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "f758483df5d5a9c66042e1a841bc15110cf248cb57e5fc65b76a947021d5370d"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
git-tree-sha1 = "1ac67cec4b5bfc8c62418b2566479fa3cd2c227f"
os = "macos"

    [[Chemfiles.download]]
    sha256 = "e11f9d3206113ed17503ccb59d19b19caa973bcf91213fee172874a8e0902e1f"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.x86_64-apple-darwin.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "963bf538d2fc20dabf5c5d582d4b1c0421d5c30d"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "e34e3afb5ac4589df84ad2c291afe9a97fab027d0c12d070b894ac59fa22cd6a"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "529df6d2547d8d38e8eb92ca546c88c1977c37a9"
libc = "glibc"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "10ebcf1cb6c0c3a0ef8473fae12065d655258ae8ca7438edef623404216f95e4"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6461ce3c7d6058bc1af16f99c135437aee5ab139"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "d2b2a5edab4e3f06bf7a0b21191f5bada92fa2ac1d1e50f52d085b65fa332d9d"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.x86_64-linux-musl-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c71cc3009753e2c0bdbb31e356449e8d01243ed"
libc = "musl"
os = "linux"

    [[Chemfiles.download]]
    sha256 = "f9973b3449a6641bb237a301d8cedb733667ad99a020817250d119912e3c0804"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.x86_64-linux-musl-cxx11.tar.gz"
[[Chemfiles]]
arch = "x86_64"
git-tree-sha1 = "ba112b8f345d0727aa676b3406d81cbc8fa5b860"
os = "freebsd"

    [[Chemfiles.download]]
    sha256 = "d2d1d4544b4e5d9b86f5b78aefd0c650c9ee5508770bdf47bf4fe23b388b7e7a"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.x86_64-unknown-freebsd.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b2096e67ff5b3c0effa6bcb924c645913985d8f"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "bd57055f501d6b5240b4c87f0fe3aba97db8e90367e9ca0ec0c0afc9bb1905af"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Chemfiles]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7cefd48c527f8d3af572e522b5d50d323ba55eb"
os = "windows"

    [[Chemfiles.download]]
    sha256 = "55d05f2a26611edae6d5898d45a623e4cb8ffd877e80ac2d82f4da68396bac03"
    url = "https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/releases/download/Chemfiles-v0.10.3+0/Chemfiles.v0.10.3.x86_64-w64-mingw32-cxx11.tar.gz"
